# Generated by Django 4.2.3 on 2024-01-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StageData',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('promo', models.CharField(max_length=9)),
                ('numEtudiant', models.IntegerField()),
                ('prof', models.CharField(max_length=255)),
                ('tuteur', models.CharField(max_length=255)),
                ('Entreprise', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('année', models.IntegerField()),
                ('cr', models.FileField(help_text='Upload a PDF file', upload_to='pdfs/')),
            ],
            options={
                'verbose_name_plural': 'StageData',
            },
        ),
    ]
