# Generated by Django 4.2.3 on 2024-01-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('nSiret', models.IntegerField(primary_key=True, serialize=False)),
                ('fJuridique', models.CharField(max_length=10)),
                ('rSociale', models.IntegerField()),
                ('adresse', models.CharField(max_length=255)),
                ('suite', models.CharField(max_length=255)),
                ('codeP', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('Tele', models.CharField(max_length=10)),
                ('FAX', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('teleContact', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='StageData',
        ),
    ]
