# Generated by Django 4.2.3 on 2024-01-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_entreprise_delete_stagedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='nSiret',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='rSociale',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='suite',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
