# Generated by Django 4.2.3 on 2024-01-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_etudiant_professeur_stage_alter_entreprise_tele_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='suite',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
