# Generated by Django 4.2.3 on 2024-01-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_stage_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='suite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
