# Generated by Django 4.2.3 on 2024-01-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_professeur_suite'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='nom',
            field=models.CharField(default='entreprise', max_length=255),
        ),
    ]
